### ISSUE TITLE
UTF8 subject not decoded correctly

### ISSUE THREAD

**Issue by peterkrejci** [DusanKasan/parsemail#1]
Subject is parsed directly from mail source without any decoding, so if it is encoded as `=?UTF-8?B?...` then you get it as it is

**Comment by DusanKasan** [comment]
Done in https://github.com/DusanKasan/parsemail/commit/f4376a629efd9d465415cc2016bd2564f74a1494

**Comment by lechuhuuha** [comment]
> Done in [f4376a6](https://github.com/DusanKasan/parsemail/commit/f4376a629efd9d465415cc2016bd2564f74a1494)

now its can decode utf8 but subject lost some space in subject 
from this 
`longvanren thân mến, bạn đã nhận được lì xì lên đến 2 triệu đồng từ Zozo`
to this
`longvanrenthân mến, bạn đã nhận được lì xì lên đến 2triệu đồng từ Zozo`

i use the lastest version from this repo and encounter this error

here is the full email https://anotepad.com/notes/mx8k3622

@DusanKasan
