### ISSUE TITLE
Unknown multipart/mixed nested mime type: text/html

### ISSUE THREAD

**Issue by jrkt** [DusanKasan/parsemail#17]
I am getting this error when trying to parse emails sent from Outlook365:

    Unknown multipart/mixed nested mime type: text/html

The email configuration inside of Outlook365 is:

> Server Name: smtp.office365.com
> Port: 587
> SSL/TLS: true 

Is there any known issues with `text/html` mime types or with TLS?

**Comment by DusanKasan** [comment]
Thanks for reporting this. It's a bug in parsing multipart/mixed. Will have a look at it asap.

**Comment by jrkt** [comment]
Any update on this?
