### ISSUE TITLE
Test does not compile

### ISSUE THREAD

**Issue by lutzhorn** [DusanKasan/parsemail#4]
The test does not compile, this line

https://github.com/DusanKasan/parsemail/blob/abc648830b9a1e9440c2c817a42a73a17c0d0c64/parsemail_test.go#L255

has this error:

    cannot use m (type *mail.Message) as type io.Reader in argument to Parse:
    *mail.Message does not implement io.Reader (missing Read method)

What are you trying to do here? `message.Message` looks like this:

```go
type Message struct {
	Header Header
	Body   io.Reader
}
```

You *could* call `Parse(m.Body)` but this would fail the tests because the body does not contain the headers.

**Comment by CSTDev** [comment]
Looks like it's call to mail.ReadMessage that's not needed, that's the first thing that Parse does.
https://github.com/DusanKasan/parsemail/blob/abc648830b9a1e9440c2c817a42a73a17c0d0c64/parsemail.go#L23-L24

I've removed it from the test in PR #5

**Comment by DusanKasan** [comment]
Resolved
